name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
          cache: false

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_windows_x64.exe
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_x64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_arm64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_arm
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_386
          CGO_ENABLED=0 GOOS=linux GOARCH=loong64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_loong64
          CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_mips
          CGO_ENABLED=0 GOOS=linux GOARCH=mips64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_mips64
          CGO_ENABLED=0 GOOS=linux GOARCH=mips64le go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_mips64le
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_mipsle
          CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_ppc64
          CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_ppc64le
          CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_riscv64
          CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_linux_s390x
          CGO_ENABLED=0 GOOS=netbsd GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_netbsd_386
          CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_netbsd_x64
          CGO_ENABLED=0 GOOS=netbsd GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_netbsd_arm
          CGO_ENABLED=0 GOOS=netbsd GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_netbsd_arm64
          CGO_ENABLED=0 GOOS=openbsd GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_openbsd_386
          CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_openbsd_x64
          CGO_ENABLED=0 GOOS=openbsd GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_openbsd_arm
          CGO_ENABLED=0 GOOS=openbsd GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_openbsd_arm64
          CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_freebsd_386
          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_freebsd_x64
          CGO_ENABLED=0 GOOS=freebsd GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_freebsd_arm
          CGO_ENABLED=0 GOOS=freebsd GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_freebsd_arm64
          CGO_ENABLED=0 GOOS=freebsd GOARCH=riscv64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_freebsd_riscv64
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_darwin_x64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_darwin_arm64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Development Build
          prerelease: true
          files: |
            file_zip_windows_x64.exe
            file_zip_linux_x64
            file_zip_linux_arm64
            file_zip_linux_arm
            file_zip_linux_386
            file_zip_linux_loong64
            file_zip_linux_mips
            file_zip_linux_mips64
            file_zip_linux_mipsle
            file_zip_linux_mips64le
            file_zip_linux_ppc64
            file_zip_linux_ppc64le
            file_zip_linux_riscv64
            file_zip_linux_s390x
            file_zip_netbsd_386
            file_zip_netbsd_x64
            file_zip_netbsd_arm
            file_zip_netbsd_arm64
            file_zip_openbsd_386
            file_zip_openbsd_x64
            file_zip_openbsd_arm
            file_zip_openbsd_arm64
            file_zip_freebsd_386
            file_zip_freebsd_x64
            file_zip_freebsd_arm
            file_zip_freebsd_arm64
            file_zip_freebsd_riscv64
            file_zip_darwin_x64
            file_zip_darwin_arm64
