name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
          cache: false

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o file_zip_win32_x64.exe

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest2"
          title: Development Build For One Files
          prerelease: true
          files: |
            file_zip_win32_x64.exe
